server:
  port: 9092
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp_db?serverTimezone=UTC
    username: root
    password: 123456
  # 设置Spring的符号日志信息不打印
  main:
    banner-mode: off
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置不打印 mybatis-plus的符号日志信息
  global-config:
    banner: false